locale: "en-US"
name: "Noushin Nabavi, PhD"
description: "Cell biologist | Data scientist"
location: "British Columbia, Canada"
repository: "NoushinN/noushinn.github.io"
header: /images/mast.jpg

avatar: "https://avatars.githubusercontent.com/u/37668936?s=400&u=e4f7d5c6218a0ec4f71820f603f075805a944c03&v=4"

url: "https://noushinn.github.io"
baseurl: ""

header_pages:
  - about.md
  - publications.md
  - software.md
  - professional-activities.md
  - awards.md

google_analytics: G-5LJV5S16HQ